title: Work in progress
author: Ivan Frias
email: frias.ivan@gmail.com
description: >-
  Hi, I'm Ivan, a software developer from Portugal. This is my gateway to the internet.
baseurl: "/"
url: "https://ivanfrias.github.io"
twitter_username: ifrias
github_username:  ivanfrias
facebook_username:  ivan.m.frias
linkedin_username: ivan-frias
rss: rss

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"

jekyll_compose:
    auto_open: true
