texture:
  title: Ivan Frias
  tagline: Software Development made right.
  author: Ivan Frias
  dateformat: "%b %-d, %Y"
  social_links:
    twitter: ifrias
    github: ivanfrias
    linkedIn: in/ivan-frias
    rss: rss
  style: black 
  showNav: true
  navigation:
    - title: About
      url: "/about"
    - title: Home
      url: "/"
  showPicker: false
email: frias.ivan@gmail.com

description: >-
  Hi, I'm Ivan, a software developer from Portugal. This is my gateway to the internet.

baseurl: ""
url: "https://ivanfrias.github.io"

# Build settings
markdown: kramdown
remote_theme: samarsault/texture
theme: texture
plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_excerpts: true

jekyll_compose:
    auto_open: true
